### ISSUE TITLE
pipenv使って環境構築したい

### ISSUE THREAD

**Issue by howmuch515** [tdu-isl/cuckoo-vm#16]

**Comment by howmuch515** [comment]
cuckoo本体をpipenvでインストールすると、起動するときにディレクトリを移動した上でpipenvからcuckooコマンドを打つ必要があるためやめる

**Comment by Syuukakou** [comment]
Cuckoo sandboxのdocumentから
、pipenvと同じ、
＞Although the above, a global installation of Cuckoo in your OS works mostly fine, we highly recommend installing Cuckoo in a virtualenv, which looks roughly as follows:
$ virtualenv venv
$ . venv/bin/activate
(venv)$ pip install -U pip setuptools
(venv)$ pip install -U cuckoo
Some reasons for using a virtualenv:
Cuckoo’s dependencies may not be entirely up-to-date, but instead pin to a known-to-work-properly version.
The dependencies of other software installed on your system may conflict with those required by Cuckoo, due to incompatible version requirements (and yes, this is also possible when Cuckoo supports the latest version, simply because the other software may have pinned to an older version).
Using a virtualenv allows non-root users to install additional packages or upgrade Cuckoo at a later point in time.
And simply put, virtualenv is considered a best practice.
Please refer to Cuckoo Working Directory and Cuckoo Working Directory Usage to learn more about the Cuckoo Working Directory and how to operate it.
